# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  modules-download-mode: readonly

# list of useful linters could be found at https://github.com/golangci/awesome-go-linters
linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - golint

issues:
  exclude-use-default: false
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
        - errcheck
      path: "_test.go"
      text: "Error return value of `(cc|con(ns?)?|db|closer|lis(tener)?).Close` is not checked"
    - linters:
        - golint
      path: "_test.go"
      text: "context.Context should be the first parameter of a function"
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
