# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  modules-download-mode: readonly

# list of useful linters could be found at https://github.com/golangci/awesome-go-linters
linters:
  disable-all: true
  enable:
    - deadcode
    - gci
    - goimports
    - gosimple
    - govet
    - ineffassign
    - maligned
    - megacheck
    - misspell
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - unused
    - unconvert
    - varcheck

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # govet checks all struct initializations must be keyed by field names
    - linters:
        - govet
      text: "composite literal uses unkeyed fields"
    - path: "_test.go"
      linters:
        - maligned
        - noctx
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
