version: "3.5"
services:
  praefect:
    build:
      context: ../../
      dockerfile: Dockerfile.praefect
    image: praefect:latest
    depends_on:
      - gitaly-primary
      - gitaly-backup-1
      - gitaly-backup-2
    command: ["/etc/gitaly/praefect", "-config", "/etc/gitaly/config.praefect.toml"]
    ports:
      - "2305:2305"
    volumes:
      - ./config.praefect.toml:/etc/gitaly/config.praefect.toml
  gitaly-primary:
    image: registry.gitlab.com/gitlab-org/build/cng/gitaly:latest
    expose:
      - "9999"
    volumes:
      - ./gitaly-primary/data:/var/opt/gitlab/git-data
      - ./config.toml:/etc/config/config.toml
  gitaly-backup-1:
    image: registry.gitlab.com/gitlab-org/build/cng/gitaly:latest
    expose:
      - "9999"
    volumes:
      - ./gitaly-backup-1/data:/var/opt/gitlab/git-data
      - ./config.toml:/etc/config/config.toml
  gitaly-backup-2:
    image: registry.gitlab.com/gitlab-org/build/cng/gitaly:latest
    expose:
      - "9999"
    volumes:
      - ./gitaly-backup-2/data:/var/opt/gitlab/git-data
      - ./config.toml:/etc/config/config.toml