- name: wait gitlab
  uri:
    url: "http://{{ groups.gitlabs[0] }}"
  register: result
  until: result.status == 200
  retries: 60
  delay: 5
  changed_when: false

- name: verify gitaly configuration
  command:
    cmd: gitlab-rake gitlab:gitaly:check

- name: verify gitlab-shell
  command:
    cmd: /opt/gitlab/embedded/service/gitlab-shell/bin/check -config /opt/gitlab/embedded/service/gitlab-shell/config.yml
  delegate_to: '{{ item }}'
  with_items: '{{ groups.gitalies }}'
