# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test.proto for package 'gitaly'

require 'grpc'
require 'test_pb'

module Gitaly
  module TestService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.TestService'

      # TestSidechannel lets a client test if it can establish a sidechannel connection to a Gitaly server.
      rpc :TestSidechannel, Gitaly::TestSidechannelRequest, Gitaly::TestSidechannelResponse
    end

    Stub = Service.rpc_stub_class
  end
end
