# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'

require 'lint_pb'
require 'shared_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("test.proto", :syntax => :proto3) do
    add_message "gitaly.TestSidechannelRequest" do
      optional :repository, :message, 1, "gitaly.Repository"
    end
    add_message "gitaly.TestSidechannelResponse" do
    end
  end
end

module Gitaly
  TestSidechannelRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.TestSidechannelRequest").msgclass
  TestSidechannelResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.TestSidechannelResponse").msgclass
end
